### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by valeryjacobs** [jmservera/node-red-webapp#1]
Hi Juan,

Great idea, this template! I only have the issue that I can't deploy it as it gives met this message in the activity log:
"fatal: I don't handle protocol ' https'\n\r\nD:\Program Files (x86)\Git\cmd\git.exe fetch origin --progress"

I understood this could be caused by an illegal character in one of the template files (and I noticed there is a leading space in the error text, not sure if that's the root cause).

**Comment by jmservera** [comment]
Hi Valery, I've updated the template and tested it, can you check if you still experience the issue? Thanks!

**Comment by jmservera** [comment]
After some tests I think it is fixed. I close it, if you find any issue please reopen it. Thanks for your feedback.
