### ISSUE TITLE
Node red azure

### ISSUE THREAD

**Issue by kasuntheekshana** [jmservera/node-red-webapp#2]
Node red dash board not shown why is that

**Comment by JonSilver** [comment]
It's been working here - I had these settings in the `module.exports` section in settings.js:

```
httpNodeRoot: "/api",
ui: { path: "/dashboard" },
```

**Comment by jmservera** [comment]
Hi, as explained in the readme, the dashboard is in the /ui path, but you can change it in the settings.js if you want. I'm going to update the template to provide some more options, do you want this to be configurable?

**Comment by jmservera** [comment]
Ok, looks like something is broken. Will update the template ASAP.

**Comment by jmservera** [comment]
It should be visible in the /ui path. If you cannot view wait 20 seconds and refresh the page, sometimes it takes a while until all the modules are installed. 
Then check that you added the dashboard elements to a tab and a group (and that you created at least one tab with one group inside).
You should see this next to the flow:
![image](https://user-images.githubusercontent.com/8036360/37098708-d844d8c6-221e-11e8-9574-84076fe42078.png)

I'm going to update the template with new versions, do you want the path value to be configurable from the template? If yes, open an issue with this and I will add it.

**Comment by jmservera** [comment]
I've tested again and works as expected. I'm closing it, if you want this value configurable open a new issue. Thanks you.
