### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by JonSilver** [jmservera/node-red-webapp#4]
Please could the next version request node version 8.9.4 from the Azure node runtime environment, or whatever the latest available LTS is at the time of release? Also it's debatable whether to turn off Azure web app PHP support and enable 64-bit by default.

**Comment by jmservera** [comment]
Sure. By now, you can change it directly as explained here: https://blogs.msdn.microsoft.com/azureossds/2016/04/20/nodejs-and-npm-versions-on-azure-app-services/

**Comment by JonSilver** [comment]
Yes I'm aware it can be changed after deployment, but it'd be nice for a fresh deployment to already be set to latest LTS.
