### ISSUE TITLE
Project disabled as can't find git

### ISSUE THREAD

**Issue by beneuto** [jmservera/node-red-webapp#7]
Not sure if others are experiencing this but due to an apparent bug in Azure, the Application Pool path variable for Git is showing "D:\\Program Files (x86)\\Git\\cmd' when in fact the 64 bit version of Git has been installed.   This means the the Projects functionality of node-red will not work as it cannot find the Git executable.

This can be worked around by adding the following line to the server.js file:

`
process.env.Path = 'D:\\Program Files\\Git\\cmd;D:\\Program Files\\Git\\usr\\bin;' + process.env.Path;
`

**Comment by justoke** [comment]
Thank you for the tip. This is an essential bit if you want to use projects in Node-Red. I use them all the time and this makes it very easy to change your dashboards to a different project.

I would suggest this be added as default. Also the settings.js file is missing the commented out section to enable projects. Add this, if you want to enable projects along with the server.js suggestion.

```
editorTheme: {
       projects: {
           enabled: true
       }
   }
```

The latest node-red it now at 0.20.7, so it would be nice if these things were updated. This is such a useful project. Thank you for sharing!

**Comment by jmservera** [comment]
Nice suggestions, thanks. I added the path and enabled projects.
